name: Build and Push Reprocess mediator image

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - devops-fix

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build and push tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocess-mediator/Dockerfile
          tags: kevmurumba/reprocess-mediator:${{ github.ref_name }}
          build-args: |
            NETWORK_TIMEOUT=600000

      - name: Build and push ui tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocessor-mediator-microfrontend/Dockerfile
          tags: kevmurumba/reprocess-mediator-ui:${{ github.ref_name }}
          build-args: |
            NETWORK_TIMEOUT=600000

      - name: Build and push latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocess-mediator/Dockerfile
          tags: kevmurumba/reprocess-mediator:latest
          build-args: |
            NETWORK_TIMEOUT=600000

      - name: Build and push ui latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocessor-mediator-microfrontend/Dockerfile
          tags: kevmurumba/reprocess-mediator-ui:latest
          build-args: |
            NETWORK_TIMEOUT=600000
