name: Build and Push Reprocess mediator image

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - devops-fix

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: apps/reprocess-mediator/Dockerfile
          tags: kevmurumba/reprocess-mediator:${{ github.ref_name }}

      - name: Build and push ui tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: apps/reprocessor-mediator-microfrontend/Dockerfile
          tags: kevmurumba/reprocess-mediator-ui:${{ github.ref_name }}

      - name: Build and push latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: apps/reprocess-mediator/Dockerfile
          tags: kevmurumba/reprocess-mediator:latest

      - name: Build and push ui latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          file: apps/reprocessor-mediator-microfrontend/Dockerfile
          tags: kevmurumba/reprocess-mediator-ui:latest
