name: Build and Push Reprocess mediator image

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocess-mediator/Dockerfile
          tags: jembi/reprocess-mediator:${{ github.ref_name }}

      - name: Build and push ui tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocessor-mediator-microfrontend/Dockerfile
          tags: jembi/reprocess-mediator-ui:${{ github.ref_name }}

      - name: Build and push latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocess-mediator/Dockerfile
          tags: jembi/reprocess-mediator:latest

      - name: Build and push ui latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: apps/reprocessor-mediator-microfrontend/Dockerfile
          tags: jembi/reprocess-mediator-ui:latest
